name: Generate Snake Animation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Adicione seus passos de build/dist aqui

      - name: Configurar usuário do git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push dist directory to output branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git
          git fetch origin output || git checkout -b output
          git add dist/
          git commit -m "Atualizando dist via GitHub Actions" || echo "Nada para commitar"
          git push --force origin output
